import Head from 'next/head';
import { useJobTracker } from '../../context/JobTrackerContext';
import JobTrackerLayout from '../../components/JobTrackerLayout';
import Link from 'next/link';

export default function JobTrackerDigest() {
    const { digest, generateDigest, loadDigest, preferences, status } = useJobTracker();

    if (!preferences || Object.keys(preferences).length === 0) {
        return (
            <JobTrackerLayout>
                <Head>
                    <link rel="stylesheet" href="/styles/job-tracker/reset.css" />
                    <link rel="stylesheet" href="/styles/job-tracker/variables.css" />
                    <link rel="stylesheet" href="/styles/job-tracker/layout.css" />
                    <link rel="stylesheet" href="/styles/job-tracker/components.css" />
                </Head>
                <div className="container context-header">
                    <h1>Daily Digest</h1>
                    <p>Your curated list of top opportunities.</p>
                </div>
                <div className="container">
                    <div className="state-card" style={{ background: '#fff3e0', borderColor: '#ffe0b2' }}>
                        <h4 style={{ color: '#e65100' }}>Preferences Required</h4>
                        <p>To generate your personalized daily digest, we need to know what you're looking for.</p>
                        <Link href="/tracker/settings" className="btn btn-secondary">Set Preferences</Link>
                    </div>
                </div>
            </JobTrackerLayout>
        );
    }

    if (!digest) {
        return (
            <JobTrackerLayout>
                <Head>
                    <link rel="stylesheet" href="/styles/job-tracker/reset.css" />
                    <link rel="stylesheet" href="/styles/job-tracker/variables.css" />
                    <link rel="stylesheet" href="/styles/job-tracker/layout.css" />
                    <link rel="stylesheet" href="/styles/job-tracker/components.css" />
                </Head>
                <div className="container context-header">
                    <h1>Daily Digest</h1>
                    <p>Your 9AM briefing is ready to be generated.</p>
                </div>
                <div className="container" style={{ textAlign: 'center', padding: '40px 0' }}>
                    <div className="card" style={{ maxWidth: '500px', margin: '0 auto', textAlign: 'center' }}>
                        <h3>Good Morning! ☀️</h3>
                        <p style={{ marginBottom: '20px', color: '#666' }}>Ready to see your top 10 matches for today?</p>
                        <button className="btn btn-primary" onClick={generateDigest}>Generate 9AM Digest (Simulated)</button>
                        <p style={{ marginTop: '16px', fontSize: '12px', color: '#999' }}>*Simulates the daily 9AM trigger</p>
                    </div>
                </div>
            </JobTrackerLayout>
        );
    }

    const today = new Date().toISOString().split('T')[0];

    // Recent Updates Logic
    const recentUpdates = [];
    Object.keys(status).forEach(id => {
        // Simple check if status date is today
        if (status[id].date === today && status[id].status !== 'Not Applied') {
            // We need to find the job title etc, but context 'jobs' is available. 
            // Ideally we should pass 'jobs' to this component or access it via context if we need details.
            // We can access it via context which we already have. 
            // But let's check if we deconstructed it. No. 
            // Let's add 'jobs' to deconstruction if needed or just use digest layout.
            // Wait, the vanilla JS version looked up job details. 
            // Let's grab jobs from context.
        }
    });

    const copyDigest = () => {
        let text = `📅 My Daily Job Digest (${digest.date})\n\n`;
        digest.jobs.forEach((j, i) => {
            text += `${i + 1}. ${j.title} at ${j.company} [${j.score}% Match]\n`;
            text += `   📍 ${j.location} (${j.mode})\n`;
            text += `   🔗 ${j.applyUrl}\n\n`;
        });
        text += `Generated by Job Notification Tracker`;
        navigator.clipboard.writeText(text);
        alert('Copied to Clipboard!');
    };

    return (
        <JobTrackerLayout>
            <Head>
                <link rel="stylesheet" href="/styles/job-tracker/reset.css" />
                <link rel="stylesheet" href="/styles/job-tracker/variables.css" />
                <link rel="stylesheet" href="/styles/job-tracker/layout.css" />
                <link rel="stylesheet" href="/styles/job-tracker/components.css" />
            </Head>
            <div className="container context-header">
                <h1>Daily Digest</h1>
                <p>Top 10 opportunities curated for you.</p>
            </div>
            <div className="container">
                <div style={{ display: 'flex', justifyContent: 'center', gap: '12px', marginBottom: '24px' }}>
                    <button className="btn btn-secondary btn-sm" onClick={copyDigest}>Copy to Clipboard</button>
                    <button className="btn btn-secondary btn-sm" onClick={() => alert('Email draft feature coming soon!')}>Create Email Draft</button>
                </div>

                <div className="digest-container">
                    <div className="digest-header">
                        <h2>Top 10 Jobs For You</h2>
                        <div className="digest-date">{new Date(digest.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
                    </div>
                    <div className="digest-body">
                        <div className="digest-intro">
                            Here are the highest matching roles found for your profile today.
                        </div>
                        <div className="digest-list">
                            {digest.jobs.map(job => (
                                <div key={job.id} className="digest-item">
                                    <div className="digest-item-content">
                                        <a href={job.applyUrl} target="_blank" className="digest-item-title">{job.title}</a>
                                        <div className="digest-item-sub">
                                            {job.company} • {job.location}
                                            <span className="digest-score">{job.score}% Match</span>
                                        </div>
                                    </div>
                                    <a href={job.applyUrl} target="_blank" className="btn btn-primary btn-sm">Apply</a>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </JobTrackerLayout>
    );
}
